### PR TITLE
Removing functionality that is now in finalize collection

### PR DESCRIPTION
**Pull request by pcoleman**
## Overview
With finalize collection, we no longer need to handle many of the legacy cases that finalize record was originally a stop gap for. This removes all of the unnecessary functionality from this method.

### CODE REVIEW

**Comment by hessmjr** [comment]
Looks like quite a few helpers still remain.

**Comment by pcoleman** [comment]
@hessmjr I just removed the helper methods that seemed finalize record specific. I left the rest since they are used in apps directly.

**Comment by hessmjr** [comment]
Hmm, they shouldn't be.  From what I could tell those were all helpers to finalizeRecord.  We may need to consult with crawl devs to make sure though.

**Comment by hessmjr** [comment]
@pcoleman yeah i just took a handful of the individual helpers and searched the Voltron80apps repo, none of them are in use directly.  I think they can all go

**Comment by pcoleman** [comment]
@hessmjr when harrison finishes lets talk to him to make sure. I check the base app and they aren't referenced in the finalize record method either. So they may be completely deprecated at this point.

**Comment by pcoleman** [comment]
@hessmjr ok removed those methods.

**Comment by hessmjr** [comment]
@pcoleman this looks good, we'll want to wait till finalize collection is in use before deploying

**Pull request merged**
